"""empty message

Revision ID: 14aaff0db4f0
Revises: ab2cf7f67f8d
Create Date: 2024-04-28 09:27:34.236371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14aaff0db4f0'
down_revision: Union[str, None] = 'ab2cf7f67f8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
