"""empty message

Revision ID: 464cf723c1c9
Revises: ebad161db914
Create Date: 2024-04-19 06:57:08.161645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '464cf723c1c9'
down_revision: Union[str, None] = 'ebad161db914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifycation_codes', sa.Column('expiry_time', sa.DateTime(), nullable=False))
    op.drop_column('verifycation_codes', 'verification_status')
    op.drop_column('verifycation_codes', 'try_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verifycation_codes', sa.Column('try_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('verifycation_codes', sa.Column('verification_status', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('verifycation_codes', 'expiry_time')
    # ### end Alembic commands ###
