"""empty message

Revision ID: 7802c9629311
Revises: 23b3e92761e7
Create Date: 2024-04-14 19:59:02.872286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7802c9629311'
down_revision: Union[str, None] = '23b3e92761e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_role_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('users_role_fkey', 'users', 'roles', ['role'], ['id'])
    # ### end Alembic commands ###
