"""empty message

Revision ID: 85764cdc98de
Revises: 84f4ade0d6c9
Create Date: 2024-04-17 07:35:48.028430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85764cdc98de'
down_revision: Union[str, None] = '84f4ade0d6c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'roles', ['role'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
