"""empty message

Revision ID: 85f1221fc186
Revises: f2703ef96f84
Create Date: 2024-05-03 06:29:14.665199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85f1221fc186'
down_revision: Union[str, None] = 'f2703ef96f84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('subscriptions_subscriber_id_fkey', 'subscriptions', type_='foreignkey')
    op.drop_constraint('subscriptions_target_id_fkey', 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'users', ['subscriber_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'subscriptions', 'users', ['target_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.create_foreign_key('subscriptions_target_id_fkey', 'subscriptions', 'users', ['target_id'], ['id'])
    op.create_foreign_key('subscriptions_subscriber_id_fkey', 'subscriptions', 'users', ['subscriber_id'], ['id'])
    # ### end Alembic commands ###
