"""empty message

Revision ID: 98eae8ebafdd
Revises: 910a59427359
Create Date: 2024-04-23 09:48:31.774362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98eae8ebafdd'
down_revision: Union[str, None] = '910a59427359'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('verifycation_codes_user_id_fkey', 'verifycation_codes', type_='foreignkey')
    op.create_foreign_key(None, 'verifycation_codes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verifycation_codes', type_='foreignkey')
    op.create_foreign_key('verifycation_codes_user_id_fkey', 'verifycation_codes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
