"""empty message

Revision ID: f2703ef96f84
Revises: 67f944c64cc3
Create Date: 2024-04-30 11:04:20.485464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2703ef96f84'
down_revision: Union[str, None] = '67f944c64cc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('hash_id', sa.VARCHAR(length=256), nullable=True))
    op.drop_constraint('messages_id_hash_key', 'messages', type_='unique')
    op.create_unique_constraint(None, 'messages', ['hash_id'])
    op.drop_column('messages', 'id_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('id_hash', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'messages', type_='unique')
    op.create_unique_constraint('messages_id_hash_key', 'messages', ['id_hash'])
    op.drop_column('messages', 'hash_id')
    # ### end Alembic commands ###
